TreeNode *menu_insert_from_file(TreeNode*, char*);
void menu_write_in_file(TreeNode*, char*);
TreeNode *menu_insert(TreeNode*);
TreeNode *menu_insert_edge(TreeNode*);
void menu_delete_edge(TreeNode*);
void menu_modify_edge(TreeNode*);
TreeNode *menu_delete(TreeNode*);
void menu_cycles_find(TreeNode*);
void menu_find_cycles(TreeNode*);
void menu_traceflow(TreeNode*);
void menu_receiving_edges(TreeNode*);
void menu();
